#!/usr/bin/env zsh

function _ZPM_log() {
  if [[ -n "$DEBUG" &&  "${1}:" == "${DEBUG}:"*  ]]; then
    num=0

    for i in $(seq 1 ${#1}); do
      num=$(( $num + $(LC_CTYPE=C printf '%d' "'${1[$i]})") ))
    done

    color=$(( $num % 6 + 1 ))

    echo -n "[1;3${color}m$1 [0m"

    shift
    echo "$@"
  fi
}