#!/usr/bin/env zsh

function _ZPM_get_plugin_type() {
  if [[ "$1" == 'zpm' ]]; then
    echo 'zpm'
    return 0
  fi

  local _ZPM_tag_str=${1##*,type:}
  _ZPM_tag_str=${_ZPM_tag_str%%\,*}

  if [[ "$_ZPM_tag_str" == *'gitlab'* ]]; then
    echo 'gitlab'
    return 0
  fi

  if [[ "$_ZPM_tag_str" == *'bitbucket'* ]]; then
    echo 'bitbucket'
    return 0
  fi

  if [[ "$1" == 'omz/'* ]]; then
    echo 'omz'
    return 0
  fi

  if [[ "$_ZPM_tag_str" == *'omz'* ]]; then
    echo 'omz'
    return 0
  fi

  echo "github"
}