#!/usr/bin/env zsh

local namespace="$1"
[[ -n "$namespace" ]] || return 0

if [[ -z "$DEBUG" || "${namespace}:" != ${DEBUG}:* ]]; then
  return 0
fi

shift

local hash=0
local idx=1
local char
while [[ $idx -le ${#namespace} ]]; do
  char=${namespace[$idx]}
  hash=$(( hash + $(LC_CTYPE=C printf '%d' "'${char}") ))
  idx=$(( idx + 1 ))
done

local color=$(( hash % 6 + 1 ))

printf '\033[1;3%sm%s \033[0m' "$color" "$namespace"

local arg
for arg in "$@"; do
  printf ' %s' "$arg"
done

printf '\n'
