#!/usr/bin/env zsh

local plugin_spec="$1"
local plugin_path="$2"
local plugin_basename="$3"
local plugin_origin_type="$4"

local destination='plugin'
if [[ "$plugin_spec" == *",destination:"* ]]; then
  destination="${${plugin_spec##*,destination:}%%,*}"
fi

case "$plugin_origin_type" in
  git|dir-link)
    print -r -- "$plugin_path"
    return 0
    ;;
  remote|file-link|exec)
    case "$destination" in
      completion)
        print -r -- "${plugin_path}/functions/_${plugin_basename}"
        ;; 
      bin)
        print -r -- "${plugin_path}/bin/${plugin_basename}"
        ;; 
      *)
        print -r -- "${plugin_path}/${plugin_basename}.zsh"
        ;;
    esac
    return 0
    ;;
  *)
    print -r -- "$plugin_path"
    return 0
    ;;
esac
