#!/usr/bin/env zsh

local plugin_name="$1"

plugin_name=${plugin_name##*\/}

plugin_name=${plugin_name##oh-my-zsh-}
plugin_name=${plugin_name##zsh-}
plugin_name=${plugin_name%%.zsh}
plugin_name=${plugin_name%%-zsh}
plugin_name=${plugin_name%%.plugin}

echo "${plugin_name}"

