#!/usr/bin/env zsh

typeset -a _Plugins_Upgrade=($@)
typeset -a _Plugins_Upgrade_full=()

if [[ -z $@ ]]; then
  _Plugins_Upgrade=("@zpm" $zsh_loaded_plugins)
fi

for plugin (${_Plugins_Upgrade}); do
  _Plugins_Upgrade_full+=($_ZPM_plugins_full[$plugin])
done

@zpm-launch-plugin-helper upgrade "${_Plugins_Upgrade_full[@]}"

@zpm-clean
