#!/usr/bin/env zsh

local Plugin_name="$1"
declare -Ag plugin_origin_types=(
  empty empty

  gh git
  github git
  gl git
  gitlab git
  bb git
  bitbucket git
  git git

  file file
  omz-theme file
  omz-lib file

  dir dir
  link dir
  omz dir

  remote remote
  gist remote
)

if [[ "$Plugin_name" == "@"* ]]; then
  if [[ "$Plugin_name" == '@zpm' ]]; then
    echo 'git'
    return 0
  fi

  if [[ "$Plugin_name" == '@omz' ]]; then
    echo 'git'
    return 0
  fi

  for plugin_origin_type_key plugin_origin_type in ${(@kv)plugin_origin_types}; do
    if [[ "$Plugin_name" == "@${plugin_origin_type_key}/"* || "$Plugin_name" == "@${plugin_origin_type_key}" ]];then
      echo "$plugin_origin_type"
      return 0
    fi
  done

  return -1
fi

if [[ "$Plugin_name" = *'/'* && "$Plugin_name" != *'/'*'/'* ]]; then
  echo 'git'
  return 0
fi

return -1
