#!/usr/bin/env zsh
TMOUT=5
add-zsh-hook -d background @zpm-background-initialization
rehash
compinit -i -d "${_ZPM_COMPDUMP}"

local _ZPM_TMP="$(mktemp)"
local _ZPM_TMP_ASYNC="$(mktemp)"

echo "_zpm_cache=true" >> "$_ZPM_TMP"
echo "autoload -Uz -- $_ZPM_autoload" >> "$_ZPM_TMP"
echo >> "$_ZPM_TMP"

echo 'compinit -i -C -d "${_ZPM_COMPDUMP}"' >> "$_ZPM_TMP"
echo >> "$_ZPM_TMP"

for plugin in ${_ZPM_plugins_for_source}; do
  local file="$_ZPM_file_for_source["$plugin"]"
  echo "(){" >> "$_ZPM_TMP"
  echo "ZERO='${file}'" >> "$_ZPM_TMP"
  cat "${file}" >> "$_ZPM_TMP"
  echo "}" >> "$_ZPM_TMP"
  echo >> "$_ZPM_TMP"
done

echo '_ZPM_post_fn () {' >> "$_ZPM_TMP"
echo "  source '$_ZPM_CACHE_ASYNC'" >> "$_ZPM_TMP"
echo '  TMOUT=5' >> "$_ZPM_TMP"
echo '  add-zsh-hook -d background _ZPM_post_fn' >> "$_ZPM_TMP"
echo '}' >> "$_ZPM_TMP"
echo >> "$_ZPM_TMP"

echo 'TMOUT=1' >> "$_ZPM_TMP"
echo >> "$_ZPM_TMP"

echo 'add-zsh-hook background _ZPM_post_fn' >> "$_ZPM_TMP"
echo >> "$_ZPM_TMP"
echo 'zpm () {}' >> "$_ZPM_TMP"

echo "$(typeset -p _ZPM_plugins_full)" >> "$_ZPM_TMP_ASYNC"
echo 'unfunction zpm' >> "$_ZPM_TMP_ASYNC"
echo >> "$_ZPM_TMP_ASYNC"

for plugin in ${_ZPM_plugins_for_async_source}; do
  local file="$_ZPM_file_for_async_source["$plugin"]"
  echo "(){" >> "$_ZPM_TMP_ASYNC"
  echo "ZERO='${file}'" >> "$_ZPM_TMP_ASYNC"
  cat "${file}" >> "$_ZPM_TMP_ASYNC"
  echo "}" >> "$_ZPM_TMP_ASYNC"
  echo >> "$_ZPM_TMP_ASYNC"
done

cat "${_ZPM_DIR}/lib/init.zsh" >> "$_ZPM_TMP_ASYNC"
echo >> "$_ZPM_TMP_ASYNC"

echo "zle && zle reset-prompt" >> "$_ZPM_TMP_ASYNC"

cat "$_ZPM_TMP" | command egrep -v '\#\!/usr/bin/env\ zsh|\#DO_NOT_INCLUDE_LINE_IN_ZPM_CACHE' >! "$_ZPM_CACHE"
cat "$_ZPM_TMP_ASYNC" | command egrep -v '\#\!/usr/bin/env\ zsh|\#DO_NOT_INCLUDE_LINE_IN_ZPM_CACHE' >! "$_ZPM_CACHE_ASYNC"

rm "$_ZPM_TMP" "$_ZPM_TMP_ASYNC"

unfunction source

(@zpm-compile 2>/dev/null &)
