#!/usr/bin/env zsh

local Plugin_name="$1"
local Plugin_type="$2"

if [[ "$Plugin_type" == 'omz' ]]; then
  echo "https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/${Plugin_name#*/}"
elif [[ "$Plugin_type" == 'github' ]]; then
  echo "https://github.com/${Plugin_name}"
elif [[ "$Plugin_type" == 'gitlab' ]]; then
  echo "https://gitlab.com/${Plugin_name}"
elif [[ "$Plugin_type" == 'bitbucket' ]]; then
  echo "https://bitbucket.com/${Plugin_name}"
elif [[ "$Plugin_type" == 'zpm' ]]; then
  echo "https://github.com/zpm-zsh/zpm"
elif [[ "$Plugin_type" == 'omz-core' ]]; then
  echo "https://github.com/ohmyzsh/ohmyzsh"
else
  return -1
fi
