#!/usr/bin/env zsh

local plugin_name="$1"

local -a plugin_origin_types=(
  empty,empty

  gh,git
  github,git
  gl,git
  gitlab,git
  bb,git
  bitbucket,git
  git,git

  file,file-link
  omz/theme,file-link
  omz/lib,file-link

  dir,dir-link
  link,dir-link
  omz,dir-link

  remote,remote
  gist,remote

  exec,exec
)

if [[ "$plugin_name" == "@"* ]]; then
  case "$plugin_name" in
    @zpm|@omz)
      print -r -- 'git'
      return 0
      ;;
  esac

  local entry entry_key entry_value
  for entry in "${plugin_origin_types[@]}"; do
    entry_key="${entry%%,*}"
    entry_value="${entry#*,}"
    if [[ "$plugin_name" == "@${entry_key}/"* ]]; then
      print -r -- "$entry_value"
      return 0
    fi
  done

  return -1
fi

if [[ "$plugin_name" == */* && "$plugin_name" != *'/'*'/'* ]]; then
  print -r -- 'git'
  return 0
fi

return -1
