#!/usr/bin/env zsh

local -a plugins_to_upgrade=($@)
local -a plugin_specs=()

if (( ${#plugins_to_upgrade} == 0 )); then
  plugins_to_upgrade=(${(k)_ZPM_plugins_full})
fi

local plugin
for plugin in "${plugins_to_upgrade[@]}"; do
  if [[ -n ${_ZPM_plugins_full[$plugin]-} ]]; then
    plugin_specs+=("${_ZPM_plugins_full[$plugin]}")
  fi
done

(( ${#plugin_specs} )) || return 0

@zpm-launch-plugin-helper upgrade "${plugin_specs[@]}"

@zpm-clean
