#!/usr/bin/env zsh

local Plugin_cause="$2"
if [[ "$Plugin_cause" == 'missing' ]]; then
  @zpm-log zpm:init:source "Plugin file for ${Plugin_name} is missing"
else
  @zpm-log zpm:init:source "Sourcing for ${Plugin_name} is disabled"
fi

_ZPM_plugins_no_source+=("$1")
