#!/usr/bin/env zsh

local Plugin="$1"
local Plugin_name="$2"
local Plugin_type="$3"

local Plugin_origin="$(@zpm-get-origin $Plugin)"

if [[ -n "$Plugin_origin" ]]; then
  echo "$Plugin_origin"
  return 0
fi

local Plugin_striped_name="${Plugin_name#@*/}"

if [[ "$Plugin_type" == 'github' ]]; then
  echo "https://github.com/${Plugin_striped_name}"
elif [[ "$Plugin_type" == 'gitlab' ]]; then
  echo "https://gitlab.com/${Plugin_striped_name}"
elif [[ "$Plugin_type" == 'bitbucket' ]]; then
  echo "https://bitbucket.com/${Plugin_striped_name}"
elif [[ "$Plugin_type" == 'omz-core' ]]; then
  echo "https://github.com/ohmyzsh/ohmyzsh"
else
  return -1
fi
