#!/usr/bin/env zsh

local plugin_name="$1"
local plugin_cause="$2"

if [[ -z "$plugin_name" ]]; then
  return 1
fi

if [[ "$plugin_cause" == 'missing' ]]; then
  @zpm-log zpm:init:source "Plugin file for ${plugin_name} is missing"
else
  @zpm-log zpm:init:source "Sourcing for ${plugin_name} is disabled"
fi

_ZPM_plugins_no_source+=("$plugin_name")
