#!/usr/bin/env zsh

local plugin_name="$1"
local plugin_type="$2"
local plugin_origin="$3"

case "$plugin_type" in
  github)
    print -r -- "https://github.com/${plugin_name}"
    ;;
  gitlab)
    print -r -- "https://gitlab.com/${plugin_name}"
    ;;
  bitbucket)
    print -r -- "https://bitbucket.com/${plugin_name}"
    ;;
  zpm)
    print -r -- 'https://github.com/zpm-zsh/zpm'
    ;;
  omz-core)
    print -r -- 'https://github.com/ohmyzsh/ohmyzsh'
    ;;
  omz)
    print -r -- "https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/${plugin_name#*/}"
    ;;
  omz-lib)
    print -r -- "https://github.com/ohmyzsh/ohmyzsh/tree/master/lib/${plugin_name#*/}.zsh"
    ;;
  omz-theme)
    print -r -- "https://github.com/ohmyzsh/ohmyzsh/tree/master/themes/${plugin_name#*/}.zsh-theme"
    ;;
  gist)
    print -r -- "https://gist.githubusercontent.com/${plugin_name#@*/}"
    ;;
  dir|file)
    print -r -- "file://${plugin_origin}"
    ;;
  *)
    return -1
    ;;
esac
