#!/usr/bin/env zsh

rehash
compinit -i -d "${_ZPM_COMPDUMP}"
unfunction source 2>/dev/null

echo "$is" >! $ZSH_TMP_DIR/is

local _ZPM_TMP="$(mktemp)"
local _ZPM_TMP_ASYNC="$(mktemp)"

{
  echo "autoload -Uz -- @zpm-clean $_ZPM_autoload"
  echo
  echo 'compinit -i -C -d "${_ZPM_COMPDUMP}"'
  echo

  for plugin in ${_ZPM_plugins_for_source}; do
    local file="$_ZPM_file_for_source["$plugin"]"
    echo "(){"
    echo "0='${file}'"

    # Workaround for powerlevel10k
    if [[ "$plugin" == "romkatv/powerlevel10k" ]]; then
      echo "export POWERLEVEL9K_INSTALLATION_DIR='$(@zpm-get-plugin-path $plugin)'"
    fi

    cat "${file}"
    echo "}"
    echo
  done

  echo "sched +0 source '$_ZPM_CACHE_ASYNC'"
  echo

  echo 'if [[ -s $ZSH_TMP_DIR/is ]]; then'
  echo '  if [[ "$is" != "$(<$ZSH_TMP_DIR/is)" ]]; then'
  echo '    @zpm-clean'
  echo '  fi'
  echo 'fi'

  echo
  echo
  echo 'zpm () {}'
} >! "$_ZPM_TMP"

{
  typeset -p _ZPM_plugins_full
  echo 'unfunction zpm'
  typeset -p _zpm_parallel_format
  typeset -p _zpm_parallel_launcher
  typeset -p _zpm_parallel_item
  echo

  for plugin in ${_ZPM_plugins_for_async_source}; do
    local file="$_ZPM_file_for_async_source["$plugin"]"
    echo "(){"
    echo "0='${file}'"

    # Workaround for powerlevel10k
    if [[ "$plugin" == "romkatv/powerlevel10k" ]]; then
      echo "export POWERLEVEL9K_INSTALLATION_DIR='$(@zpm-get-plugin-path $plugin)'"
    fi

    cat "${file}"
    echo "}"
    echo
  done

  echo "zle && zle reset-prompt"
  echo "sched +0 source ${_ZPM_DIR}/lib/init.zsh"
} >! "$_ZPM_TMP_ASYNC"

mv "$_ZPM_TMP" "$_ZPM_CACHE"
mv "$_ZPM_TMP_ASYNC" "$_ZPM_CACHE_ASYNC"

(@zpm-compile 2>/dev/null &)
