#!/usr/bin/env zsh

local raw="${1:-}"
[[ -n "$raw" ]] || return 0

local autoload_file
for autoload_file in ${(s.:.)raw}; do
  [[ -n "$autoload_file" ]] || continue
  _ZPM_autoload+=("$autoload_file")
  autoload -Uz -- "$autoload_file"
done
