#!/usr/bin/env zsh

local Plugin_name="$1"
local Plugin_link="$2"
local status_string

function join() { # usage: join ', ' "${array[@]}"
  local sep=$1 arg
  printf %s "$2"
  shift 2
  for arg do
    printf %s%s "$sep" "$arg"
  done
  printf '\n'
}

plugin_name_arr=
local -a plugin_name_arr_color

for plugin in ${(s./.)Plugin_name}; do
  if [[ "$plugin" == "@"* ]]; then
    plugin_name_arr_color=($plugin_name_arr_color "${c[cyan]}${c[bold]}${plugin}" )
  else
    plugin_name_arr_color=($plugin_name_arr_color "${c[blue]}${c[bold]}${plugin}" )
  fi
done

if [[ -z "$Plugin_link" ]]; then
  status_string="$(join "${c[red]}${c[bold]}/" $plugin_name_arr_color)"
else
  status_string="\033]8;;${Plugin_link}\a"
  status_string+="$(join "${c[red]}${c[bold]}/" $plugin_name_arr_color)"
  status_string+="\033]8;;\a${c[reset]}"
fi

echo $status_string
