#!/usr/bin/env zsh

local Plugin_name="$1"

declare -Ag plugin_types=(
  empty empty
  omz omz
  omz-theme omz-theme
  omz-lib omz-lib
  gh github
  github github
  gl gitlab
  gitlab gitlab
  bb bitbucket
  bitbucket bitbucket
)

if [[ "$Plugin_name" == "@"* ]]; then
  if [[ "$Plugin_name" == '@zpm' ]]; then
    echo 'zpm'
    return 0
  fi

  if [[ "$Plugin_name" == '@omz' ]]; then
    echo 'omz-core'
    return 0
  fi

  for plugin_type_key plugin_type in ${(@kv)plugin_types}; do
    if [[ "$Plugin_name" == "@${plugin_type_key}/"* || "$Plugin_name" == "@${plugin_type_key}" ]];then
      echo "$plugin_type"
      return 0
    fi
  done

  echo 'empty'
  return 0
fi

if [[ 'a/b' = *'/'* && 'a/b' != *'/'*'/'* ]]; then
  echo 'github'
  return 0
fi

echo 'empty'

