#!/usr/bin/env zsh

local Plugin_name="$1"
local Plugin_link="$2"
local status_string

local -a plugin_name_arr_color

for plugin in ${(s./.)Plugin_name}; do
  if [[ "$plugin" == "@"* ]]; then
    plugin_name_arr_color=($plugin_name_arr_color "${c[cyan]}${c[bold]}${plugin}" )
  else
    plugin_name_arr_color=($plugin_name_arr_color "${c[blue]}${c[bold]}${plugin}" )
  fi
done

local _sep="${c[red]}${c[bold]}/"
local _joined="${plugin_name_arr_color[1]}"
local _el
for _el in "${plugin_name_arr_color[@]:1}"; do
  _joined+="${_sep}${_el}"
done

if [[ -z "$Plugin_link" ]]; then
  status_string="$_joined"
else
  status_string="\033]8;;${Plugin_link}\a"
  status_string+="$_joined"
  status_string+="\033]8;;\a${c[reset]}"
fi

echo $status_string
