#!/usr/bin/env zsh

if [[ -n "$DEBUG" &&  "${1}:" == "${DEBUG}:"*  ]]; then
  local num=0
  local i=0

  while [[ $i -lt $(( ${#1} + 1 )) ]]; do
    num=$(( $num + $(LC_CTYPE=C printf '%d' "'${1[$i]})") ))
    i=$(( $i + 1))
  done

  color=$(( $num % 6 + 1 ))

  echo -n "[1;3${color}m$1 [0m"
  shift
  echo "$@"
fi
