#!/usr/bin/env zsh

local Plugin="$1"
local autoload_files="$2"

if [[ "$Plugin"  == *",autoload:"* ]]; then
  local _ZPM_autoload_str=${Plugin##*,autoload}
  _ZPM_autoload_str=${_ZPM_autoload_str%%\,*}
  autoload_files="${autoload_files}${_ZPM_autoload_str}"
fi

echo "$autoload_files"
