#!/usr/bin/env zsh

setopt localoptions noglobdots

zcompile "$_ZPM_CACHE" 2>/dev/null
zcompile "$_ZPM_CACHE_ASYNC" 2>/dev/null
zcompile "${_ZPM_COMPDUMP}" 2>/dev/null
zcompile "${HOME}/.zshrc" 2>/dev/null
zcompile "${HOME}/.zshrc.local" 2>/dev/null
zcompile "${_ZPM_DIR}/zpm.zsh" 2>/dev/null
zcompile "${_ZPM_DIR}/lib/init.zsh" 2>/dev/null
zcompile "${_ZPM_DIR}/lib/imperative.zsh" 2>/dev/null

for dir in $fpath; do
  if [[ -d "$dir" && -w "$dir" ]]; then
    for i in "${dir}"/**/*(N-.); do
      if [[ "${i}" != *".zwc" && "${i}" != */.git/* && ! "${i}.zwc" -nt "${i}" ]]; then
        zcompile -- "${i}" 2>/dev/null
      fi
    done
  fi
done

return 0

