#!/usr/bin/env zsh

local Plugin="$1"
local Autoload_files="$2"

if [[ "$Plugin"  == *",autoload:"* ]]; then
  local _ZPM_autoload_str=${Plugin##*,autoload}
  _ZPM_autoload_str=${_ZPM_autoload_str%%\,*}
  Autoload_files="${Autoload_files}${_ZPM_autoload_str}"
fi

echo "$Autoload_files"
