#!/usr/bin/env zsh

local Plugin="$1"
local Plugin_path="$2"

# Workaround for sindresorhus/pure
if [[ "$Plugin" == 'sindresorhus/pure' ]]; then
  echo "${Plugin_path:a}"
  return
fi

local zpm_fpath
if [[ "$Plugin" == *",fpath:"* ]]; then
  zpm_fpath="${Plugin_path}/${${1##*,fpath:}%%,*}"
  echo "${zpm_fpath:a}"
elif [[ -d "${Plugin_path}/functions" ]]; then
  zpm_fpath="${Plugin_path}/functions"
  echo "${zpm_fpath:a}"
else
  for file in "${Plugin_path}/_"*(N); do
    echo "${Plugin_path:a}"
    return
  done
fi
