#!/usr/bin/env zsh

zcompile "$_ZPM_CACHE" 2>/dev/null
zcompile "$_ZPM_CACHE_ASYNC" 2>/dev/null
zcompile "${_ZPM_COMPDUMP}" 2>/dev/null
zcompile "${HOME}/.zshrc" 2>/dev/null
zcompile "${HOME}/.zshrc.local" 2>/dev/null
zcompile "${_ZPM_DIR}/zpm.zsh" 2>/dev/null
zcompile "${_ZPM_DIR}/lib/init.zsh" 2>/dev/null
zcompile "${_ZPM_DIR}/lib/imperative.zsh" 2>/dev/null

local dir file
for dir in "${fpath[@]}"; do
  [[ -w "$dir" ]] || continue

  for file in "$dir"/**/*; do
    [[ -f "$file" ]] || continue
    if [[ "$file" != *.zwc && ! "${file}.zwc" -nt "$file" ]]; then
      zcompile -- "$file" 2>/dev/null
    fi
  done
done

return 0
