#!/usr/bin/env zsh

local Plugin_path="${1}"
local Plugin_basename="${2}"
local Plugin="${3}"

if [[ "$Plugin"  == *",source:"* ]]; then
  local Plugin_sourcefile="${${Plugin##*,source:}%%,*}"
  if [[ -n "${Plugin_sourcefile}" && -e "${Plugin_path}/${Plugin_sourcefile}" ]]; then
    echo "${Plugin_path}/${Plugin_sourcefile}"
    return 0
  else
    return -1
  fi
fi

if [[ -e "${Plugin_path}/zpm-generated.zsh" ]]; then
  echo "${Plugin_path}/zpm-generated.zsh"
  return 0
fi

if [[ -e "${Plugin_path}/${Plugin_basename}.plugin.zsh" ]]; then
  echo "${Plugin_path}/${Plugin_basename}.plugin.zsh"
  return 0
fi

if [[ -e "${Plugin_path}/zsh-${Plugin_basename}.plugin.zsh" ]]; then
  echo "${Plugin_path}/zsh-${Plugin_basename}.plugin.zsh"
  return 0
fi

if [[ -e "${Plugin_path}/${Plugin_basename}.zsh" ]]; then
  echo "${Plugin_path}/${Plugin_basename}.zsh"
  return 0
fi

if [[ -e "${Plugin_path}/${Plugin_basename}.zsh-theme" ]]; then
  echo "${Plugin_path}/${Plugin_basename}.zsh-theme"
  return 0
fi

if [[ -e "${Plugin_path}/init.zsh" ]]; then
  echo "${Plugin_path}/init.zsh"
  return 0
fi

return -1
