#!/usr/bin/env zsh

local plugin_name="$1"

local -a plugin_types=(
  empty,empty

  gh,github
  github,github

  gl,gitlab
  gitlab,gitlab

  bb,bitbucket
  bitbucket,bitbucket

  git,git

  file,file

  dir,dir
  link,dir

  omz/theme,omz-theme
  omz/lib,omz-lib
  omz,omz

  remote,remote
  gist,gist

  exec,exec
  omz-theme,omz-theme-old
  omz-lib,omz-lib-old
)

if [[ "$plugin_name" == "@"* ]]; then
  case "$plugin_name" in
    @zpm)
      print -r -- 'zpm'
      return 0
      ;;
    @omz)
      print -r -- 'omz-core'
      return 0
      ;;
  esac

  local entry entry_key entry_value
  for entry in "${plugin_types[@]}"; do
    entry_key="${entry%%,*}"
    entry_value="${entry#*,}"
    if [[ "$plugin_name" == "@${entry_key}/"* ]]; then
      print -r -- "$entry_value"
      return 0
    fi
  done

  return -1
fi

if [[ "$plugin_name" == */* && "$plugin_name" != *'/'*'/'* ]]; then
  print -r -- 'github'
  return 0
fi

return -1
