#!/usr/bin/env zsh

local Plugin_name="$1"

declare -ag plugin_types=(
  empty,empty

  gh,github
  github,github

  gl,gitlab
  gitlab,gitlab

  bb,bitbucket
  bitbucket,bitbucket

  git,git

  file,file

  dir,dir
  link,dir

  omz/theme,omz-theme
  omz/lib,omz-lib
  omz,omz

  remote,remote
  gist,gist

  exec,exec
  omz-theme,omz-theme-old
  omz-lib,omz-lib-old
)

if [[ "$Plugin_name" == "@"* ]]; then
  if [[ "$Plugin_name" == '@zpm' ]]; then
    echo 'zpm'
    return 0
  fi

  if [[ "$Plugin_name" == '@omz' ]]; then
    echo 'omz-core'
    return 0
  fi

  for plugin_type in ${plugin_types}; do
    local plugin_type_key="${plugin_type%%\,*}"
    local plugin_type="${plugin_type#*,}"
    if [[ "$Plugin_name" == "@${plugin_type_key}/"* ]];then
      echo "$plugin_type"
      return 0
    fi
  done

  return -1
fi

if [[ "$Plugin_name" = *'/'* && "$Plugin_name" != *'/'*'/'* ]]; then
  echo 'github'
  return 0
fi

return -1
