#!/usr/bin/env zsh

local Plugin="$1"
local Plugin_name="$2"
local Plugin_type="$3"

local Plugin_striped_name="${Plugin_name#@*/}"

if [[ "$Plugin" == *",origin:"* ]]; then
  local Plugin_origin="${${Plugin##*,origin:}%%,*}"

  echo "$Plugin_origin"
  return 0
fi

GITHUB_URL=${GITHUB_MIRROR:-'https://github.com'}
GITLAB_URL=${GITLAB_MIRROR:-'https://gitlab.com'}
BITBUCKET_URL=${BITBUCKET_MIRROR:-'https://bitbucket.com'}

if [[ "$Plugin_type" == 'github' ]]; then
  echo "${GITHUB_URL}/${Plugin_striped_name}"
elif [[ "$Plugin_type" == 'gitlab' ]]; then
  echo "${GITLAB_URL}/${Plugin_striped_name}"
elif [[ "$Plugin_type" == 'bitbucket' ]]; then
  echo "${BITBUCKET_URL}/${Plugin_striped_name}"
elif [[ "$Plugin_type" == 'omz-core' ]]; then
  echo "${GITHUB_URL}/ohmyzsh/ohmyzsh"
else
  return -1
fi
