#!/usr/bin/env zsh

local Plugin_path="$1"
local Plugin_type="$2"

if [[ "$Plugin_type" == "omz" ]]; then
  echo "${ZSH:-${HOME}/.oh-my-zsh}"
  return 0
fi

if [[ "$Plugin_type" == "zpm" ]]; then
  echo "${_ZPM_DIR}"
  return 0
fi

if [[ "$Plugin_type" == (github|gitlab|bitbucket) ]]; then
  echo "${Plugin_path}"
  return 0
fi

return -1
