#!/usr/bin/env zsh

local Command="$1"

local Format
local Launcher
local Item

if (( $+commands[rush] )); then
  Format='%s\n'
  Launcher="rush"
  Item='"{}"'
else
  Format='%s\0'
  Launcher="xargs -0 -P32 -n1 -I{}"
  Item='{}'
fi

shift

printf $Format "$@" | \
  ZSH_CACHE_DIR="$ZSH_CACHE_DIR" \
  _ZPM_autoload="$_ZPM_autoload" \
  ${(z)Launcher} "${_ZPM_DIR}/bin/@zpm-plugin-helper" $Command $Item
