#!/usr/bin/env zsh

# Print debug messages when DEBUG is set and the message prefix matches DEBUG.
# The prefix is shown in a deterministic colour based on its characters.
if [[ -n "$DEBUG" && "${1}:" == "${DEBUG}:"* ]]; then
  local prefix="$1"
  shift

  local num=0
  local i=1
  while (( i <= ${#prefix} )); do
    num=$(( num + $(LC_CTYPE=C printf '%d' "'${prefix[i]}'") ))
    (( i++ ))
  done
  local color=$(( num % 6 + 1 ))

  print -P "%F{${color}}${prefix}%f $*"
fi
