#!/usr/bin/env zsh

local Plugin_name="$1"
local Plugin_type="$2"

local Plugin_striped_name="${Plugin_name#@*/}"

if [[ "$Plugin_type" == 'github' ]]; then
  echo "https://github.com/${Plugin_striped_name}"
elif [[ "$Plugin_type" == 'gitlab' ]]; then
  echo "https://gitlab.com/${Plugin_striped_name}"
elif [[ "$Plugin_type" == 'bitbucket' ]]; then
  echo "https://bitbucket.com/${Plugin_striped_name}"
elif [[ "$Plugin_type" == 'omz-core' ]]; then
  echo "https://github.com/ohmyzsh/ohmyzsh"
else
  return -1
fi
