#!/usr/bin/env zsh

local plugin_name="$1"
local plugin_link="$2"

local -a colored_parts=()
local part
for part in ${(s./.)plugin_name}; do
  if [[ "$part" == @* ]]; then
    colored_parts+=("${c[cyan]}${c[bold]}${part}")
  else
    colored_parts+=("${c[blue]}${c[bold]}${part}")
  fi
done

if (( ${#colored_parts} == 0 )); then
  colored_parts=("${plugin_name}")
fi

local separator="${c[red]}${c[bold]}/"
local joined="${colored_parts[1]}"
local idx
for idx in {2..${#colored_parts}}; do
  joined+="${separator}${colored_parts[idx]}"
done

local status_string="$joined${c[reset]}"

if [[ -n "$plugin_link" ]]; then
  status_string="\033]8;;${plugin_link}\a${joined}\033]8;;\a${c[reset]}"
fi

print -r -- "$status_string"
