#!/usr/bin/env zsh

function _ZPM_addfpath() {
  _ZPM_fpath=( $_ZPM_fpath "${1}" )

  if [[ ":$FPATH:" != *":${1}:"* ]]; then
    fpath=( $fpath "${1}" )
  fi

  for i in "${1}/"*; do
    if [[ "$i" != *".zwc" && ( ! -s "$i.zwc" || "$i" -nt "$i.zwc") ]]; then;
      zcompile "$i" 2>/dev/null
    fi
  done

}
