#!/usr/bin/env zsh

function _ZPM_compile() {
  zcompile "$_ZPM_CACHE" 2>/dev/null
  zcompile "$_ZPM_CACHE_ASYNC" 2>/dev/null
  zcompile "${ZPM_COMPDUMP}" 2>/dev/null
  zcompile "${HOME}/.zshrc" 2>/dev/null
  zcompile "${HOME}/.zshrc.local" 2>/dev/null
  zcompile "${_ZPM_DIR}/zpm.zsh" 2>/dev/null

  for i in "${_ZPM_DIR}/autoload/"*; do
    if [[ -f "$i" && ( ! -s "$i.zwc" || "$i" -nt "$i.zwc") ]]; then;
      zcompile "$i" 2>/dev/null
    fi
  done

  return 0
}
