#!/usr/bin/env zsh

function _ZPM_addfpath() {
  _ZPM_fpath=( $_ZPM_fpath "${1}" )

  if [[ ":$FPATH:" != *":${1}:"* ]]; then
    fpath=( $fpath "${1}" )
  fi

  for i in "${1}/"*; do
    if [[ -f "$2" && ( ! -s "$2.zwc" || "$2" -nt "$2.zwc") ]]; then;
      zcompile "$2" 2>/dev/null
    fi
  done

}
