#!/usr/bin/env zsh

function _ZPM_async_source() {
  zsh_loaded_plugins+=("$1")

  _ZPM_plugins_for_async_source+=("$1")
  _ZPM_file_for_async_source["$1"]="${2}"

  ZERO="$2"

  source "$2"

  unset ZERO
}
