#!/usr/bin/env zsh
autoload -Uz _ZPM_get_plugin_name _ZPM_get_plugin_path

function _ZPM_readme() {
  plugins=$@
  if [[ -z $plugins ]]; then
    plugins=('zpm')
  fi

  for plugin in $plugins; do
    local Plugin_name=$(_ZPM_get_plugin_name "$1")
    local Plugin_path=$(_ZPM_get_plugin_path "$Plugin_name")

    md "${Plugin_path}/README.md"
  done
}
