#!/usr/bin/env zsh

if [[ "$1" == 'load' ]]; then
  shift
  @zpm-load-plugins "$@"
  return 0
fi

if [[ "$1" == 'if' ]]; then
  if [[ "${is[$2]}" == '1' ]] ; then
	  shift 2
    zpm "$@"
  fi
  return 0
fi

if [[ "$1" == 'if-not' ]]; then
  if [[ "${is[$2]}" == '0' ]]; then
    shift 2
    zpm "$@"
  fi
  return 0
fi

if [[ "$1" == 'u' || "$1" == 'up' || "$1" == 'upgrade' ]]; then
  shift
  @zpm-upgrade "$@"
  return 0
fi

if [[ "$1" == 'c' || "$1" == 'cl' || "$1" == 'clean' ]]; then
  @zpm-clean
  return 0
fi

if [[ "$1" == 'info' ]]; then
  shift
  zpm-info "$@"
  return 0
fi

if [[ "$1" == 'list' || "$1" == 'ls' ]]; then
  shift
  zpm-info "$@"
  return 0
fi

if [[ "$1" == 'readme' ]]; then
  shift
  zpm-readme "$@"
  return 0
fi

if [[ "$1" == 'link' ]]; then
  shift
  zpm-link "$@"
  return 0
fi

if is-callable "zpm-$1"; then
  local call_fn=$1
  shift
  "zpm-${call_fn}" $@
  return 0
fi

echo 'Unknown command `zpm '"$@"'`, treat as `zpm load '"$@"'`'
@zpm-load-plugins "$@"
