#!/usr/bin/env zsh
# Colors
color_red='31'
color_red_l='1;31'
color_green='32'
color_green_l='1;32'
color_yellow='33'
color_yellow_l='1;33'
color_blue='34'
color_blue_l='1;34'
color_purple='35'
color_purple_l='1;35'
color_cyan='36'
color_cyan_l='1;36'

color_base='37'
color_grey='38;05;246'

##################################
red=()
red_l=()
green=()
green_l=()
yellow=()
yellow_l=()
blue=()
blue_l=()
purple=()
purple_l=()
cyan=()
cyan_l=()

base=()
grey=()

##################################
#Executables
yellow+=(EXEC .cmd .exe .com .bat .reg .app .sh .csh .zsh .bin .class)
#Text
base+=(.txt .tex .org .md .markdown .mkd .todo .srt '*README' '*COPYRIGHT' '*LICENSE' '*INSTALL' '*CHANGELOG' '*AUTHORS')
#Audio
purple+=(.aac .flac .m4a .mid .midi .mp3 .ogg .wav)
#Video
red+=(.avi .flv .mkv .mov .MOV .mp4 .mpeg .mpg .ogm .ogv .ogx .vob .webm .wmv)
#Images
green+=(.jpg .jpeg .png .gif .bmp .svg .svgz .tif .tiff)
#Application archives
green+=(.apk .jar .deb .rpm .dmg .msi .xpi .crx)
#Books
red+=(.pdf .epub .fb2)
#Archives
purple+=(.7z .arj .bz .bz2 .cab .gem .gz .iso .rar .tar .tbz .tbz2 .tgz .tx .war .xz .z .Z .zip)
#Documents
cyan+=(.doc .docx .odt)

## Source files
yellow+=(.py .c .cpp .h .lua)

blue+=(.html .pug .jade .hjs .haml )
cyan_l+=(.css .less .sass .scss)
yellow+=(.js .coffee)

blue_l+=(.yml .yaml .xml .json .cson .ini .desktop)

#Other
grey+=(.log .bak .aux .~)
#################################

cp dircolors.simple dircolors
for color in red red_l green green_l yellow yellow_l \
  blue blue_l purple purple_l cyan cyan_l base grey; do
  for ex in `eval 'echo \$'$color`; do
    echo $ex `eval 'echo $color_'$color` >>dircolors
  done
done
