#!/usr/bin/env zsh
# Colors
color_red='31'
color_red_l='1;31'
color_green='32'
color_green_l='1;32'
color_yellow='33'
color_yellow_l='1;33'
color_blue='34'
color_blue_l='1;34'
color_purple='35'
color_purple_l='1;35'
color_cyan='36'
color_cyan_l='1;36'

color_base='1;37'
color_grey='1;30'

##################################
red=()
red_l=()
green=()
green_l=()
yellow=()
yellow_l=()
blue=()
blue_l=()
purple=()
purple_l=()
cyan=()
cyan_l=()

base=()
grey=()

##################################
#  #ecf0f1 #93a1a1
#  #da322f #27ad60 #d15400 #268ad1 #d5005f #00bad2
#  #e15c59 #2ecb71 #e47d22 #4da1de #fd0a77 #05e1fd
##################################

#Text
base+=(.txt .tex .org .md .markdown .mkd .todo .srt '*README' '*COPYRIGHT' '*LICENSE' '*INSTALL' '*CHANGELOG' '*AUTHORS')
#Other
grey+=(.log .bak .aux .~ .zwc .pyc)
#Documents
cyan_l+=(.doc .docx .odt)
#Video
red+=(.avi .flv .mkv .mov .MOV .mp4 .mpeg .mpg .ogm .ogv .ogx .vob .webm .wmv)
#Images
green+=(.jpg .jpeg .png .gif .bmp .svg .svgz .tif .tiff)
#Audio
purple+=(.aac .flac .m4a .mid .midi .mp3 .ogg .wav)
#Application archives
blue+=(.apk .jar .deb .rpm .dmg .msi .xpi .crx)
#Books
red_l+=(.pdf .epub .fb2)
#Archives
purple_l+=(.7z .arj .bz .bz2 .cab .gem .gz .iso .rar .tar .tbz .tbz2 .tgz .tx .war .xz .z .Z .zip)
#Executables
yellow_l+=(EXEC .cmd .exe .com .reg .app .bin .class)
# Scripts
yellow+=(.bat .sh .csh .zsh .js .coffee .py .pl .php )
## Source files
cyan_l+=(.c .cpp .h .lua .rs .pas .go .java )

blue+=(.html .pug .jade .hjs .haml )
blue_l+=(.css .less .sass .scss)

green+=(.yml .yaml .xml .json .cson .ini .desktop)
#################################

cp dircolors.simple dircolors
for color in red red_l green green_l yellow yellow_l \
  blue blue_l purple purple_l cyan cyan_l base grey; do
  for ex in `eval 'echo \$'$color`; do
    echo $ex `eval 'echo $color_'$color` >>dircolors
  done
done
